// index.js
// Advanced Math & Smart Coding Agent

// Import mathjs for advanced math operations
const math = require("mathjs");

// --- GREETING ---
console.log("🚀 Hello from your Advanced Math & Smart Coding Agent!");

// --- MATH UTILITIES ---
function mathDemo() {
  console.log("\n🔢 Math Utilities:");
  console.log("Square root of 144:", math.sqrt(144));
  console.log("Factorial of 5:", math.factorial(5));
  console.log("Matrix multiplication:", math.multiply([[1, 2]], [[3], [4]]));
  console.log("Solve equation 2x + 3 = 7:", math.solve("2x + 3 = 7", "x"));
}

// --- CODING UTILITIES ---
function codingDemo() {
  console.log("\n💻 Coding Utilities:");

  // Example: Check if a string is valid JavaScript code
  const codeSnippet = "let x = 10; console.log(x);";
  try {
    new Function(codeSnippet); // If this works, code is valid
    console.log("Code snippet is valid JavaScript!");
  } catch (err) {
    console.log("Invalid code snippet:", err.message);
  }

  // Example: Simple lint-like check (detects use of 'var')
  const lintSnippet = "var y = 5;";
  if (lintSnippet.includes("var ")) {
    console.log("Lint Warning: Avoid using 'var', use 'let' or 'const' instead.");
  }

  // Example: Auto-generate a small function
  function autoGeneratedFunction(name) {
    return `function greet${name}() { console.log("Hello, ${name}!"); }`;
  }
  console.log("Generated function:\n", autoGeneratedFunction("Jude"));
}

// --- RUN DEMOS ---
mathDemo();
codingDemo();
